# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('epc-apps', ['core','network','internet','applications','lte'])
    module.source = [
        'model/epc-application.cc',
        'model/http-client.cc',
        'model/http-server.cc',
        'model/qos-stats-calculator.cc',
        'model/real-time-video-client.cc',
        'model/real-time-video-server.cc',
        'model/stored-video-client.cc',
        'model/stored-video-server.cc',
        'model/voip-client.cc',
        'model/voip-server.cc',
        'helper/http-helper.cc',
        'helper/real-time-video-helper.cc',
        'helper/stored-video-helper.cc',
        'helper/voip-helper.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'epc-apps'
    headers.source = [
        'model/epc-application.h',
        'model/http-client.h',
        'model/http-server.h',
        'model/qos-stats-calculator.h',
        'model/real-time-video-client.h',
        'model/real-time-video-server.h',
        'model/stored-video-client.h',
        'model/stored-video-server.h',
        'model/voip-client.h',
        'model/voip-server.h',
        'helper/http-helper.h',
        'helper/real-time-video-helper.h',
        'helper/stored-video-helper.h',
        'helper/voip-helper.h',
        ]
